services:
  - type: web
    name: attendiq
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: ATTENDIQ_SECRET
        generateValue: true